### PR TITLE
Refactor to show work as a group rather than individuals

### PR DESCRIPTION
**Pull request by metazool**
*    Reorder to present list of topics as a group picture rather as individual focuses
*    Add a separate page for links and a new one for "Extras"

I've probably messed up the formatting a bit, can't persuade the version of quarto I've got locally to render nicely like the web view does

### CODE REVIEW

**Comment by jmarshrossney** [comment]
I've fixed the layout - probably the worst thing about Quarto is the use of `:::` for divs!

**Comment by jmarshrossney** [comment]
I'm completely fine with the changes, not looking to push back at all, especially since it's tomorrow and I'm not presenting.

That said, as a general observation I liked having the two-way split (a) "here's what we've been working on individually" and (b) "here's what we've been working on as a group", since I think it emphasises both our individuality and how we work as a team. On the flip side, my worry is that if everything is portrayed as a team effort with no individual contributions noted, it's easier for certain management types to imagine that the picture would look qualitatively similar with say 4 or 5 RSEs.

W definitely needed to expand the "group activities" slide, but for future/more important presentations I'd probably keep some individual focus alongside the group focus. Just my 2c!

**Comment by metazool** [comment]
> That said, as a general observation I liked having the two-way split (a) "here's what we've been working on individually" and (b) "here's what we've been working on as a group"

I liked @longr's suggested shift in emphasis from individual to group portrait of work - seeing it as moving us away from the status quo of individuals being "allocated" to projects, or of RSEs being seen as a "pool" of resources. Anything that pushes back against a short-term view of individuals assigned to different projects becoming a longer-term norm is a good thing to me.

But I hope it doesn't come across as removing personal credit :/. I personally like to work collectively, it strengthens the outcome as well as motivation, you make better lasting decisions. But I've definitely worked in the past in settings where work is collective but promotion opportunity is completely linked to individual credit and the balance is hard to hit, people are overlooked; and in settings where people gain opportunity by _associating themselves_ with credit. I don't think that's happening here, but could be wrong :)

**Comment by longr** [comment]
Thanks @metazool this looks great.   Did we put something in about the GitHub policy/advice?  Couldnt see it but may just be tired

**Comment by metazool** [comment]
> Thanks @metazool this looks great. Did we put something in about the GitHub policy/advice? Couldnt see it but may just be tired

Probably not; probably other things I missed. Please go ahead and push changes to this. We'll have the chance to expand on detail during the Steering Committee meeting and at this short notice, no-one can expect much more...

**Comment by longr** [comment]
I'm happy with this, and happy to merge it if no-one has any objections

**Pull request merged**
